# This workflow tests all code after any change to the main branch

name: CI

on:
  workflow_dispatch:

jobs:
  name: Update Changelog Webpage
  needs: [sp4-pr, sp5-full]
  runs-on: ubuntu-latest
  steps:
    - name: 🚀 Trigger Remote Workflow
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          -d "{\"ref\":\"main\"}" \
          https://api.github.com/repos/ScottPlot/ScottPlot.NET/actions/workflows/changelog.yaml/dispatches
