# run the autoformatter and commit changes back to the main branch

name: Autoformat

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**

env:
  DOTNET_VERSION: "8.0.x"

jobs:
  sp4-autoformat:
    name: Autoformat
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: ✨ Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: ✒️ ScottPlot4 Core
        run: dotnet format "src/ScottPlot4/ScottPlot/"
      - name: ✒️ ScottPlot4 Cookbook
        run: dotnet format "src/ScottPlot4/ScottPlot.Cookbook/"
      - name: ✒️ ScottPlot5 Core
        run: dotnet format "src/ScottPlot5/ScottPlot5/"
      - name: ✒️ ScottPlot5 Tests
        run: dotnet format "src/ScottPlot5/ScottPlot5 Tests/"
      - name: ✒️ ScottPlot5 Cookbook
        run: dotnet format "src/ScottPlot5/ScottPlot5 Cookbook/"
      - name: ✒️ ScottPlot5 Demo
        run: dotnet format "src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/"
      - name: 🧐 Inspect Changes
        id: verify_diff
        run: git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
      - name: ✅ Commit Changes
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --global user.name 'Scott W Harden (via GitHub Actions)'
          git config --global user.email 'swharden@gmail.com'
          git pull
          git commit -am "CI: autoformat"
          git push
