# This workflow tests all code after any change to the main branch

name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**

# cancel running versions of this workflow when this one starts
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  # PR workflows fail fast on code compile errors
  sp4-pr:
    uses: ./.github/workflows/ScottPlot4-PR.yaml
    permissions:
      security-events: write
  sp5-pr:
    uses: ./.github/workflows/ScottPlot5-PR.yaml
    permissions:
      security-events: write
  autoformat:
    uses: ./.github/workflows/task-autoformat-and-commit.yaml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # full builds take a really long time
  sp5-full:
    needs: [sp5-pr]
    uses: ./.github/workflows/ScottPlot5-Full.yaml

  # the rest are misc tasks that may as well be run after merge to main
  security:
    name: Additional Security Scan
    needs: [sp4-pr, sp5-full]
    uses: ./.github/workflows/task-security-scan.yaml
    permissions:
      security-events: write

  changelog:
    name: Publish Changelog
    needs: [sp4-pr, sp5-full]
    uses: ./.github/workflows/task-publish-changelog.yaml

  code-metrics:
    name: Publish Code Metrics
    needs: [sp4-pr, sp5-full]
    uses: ./.github/workflows/task-code-metrics.yaml
