# This workflow tests all code after any change to the main branch

name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**

# cancel running versions of this workflow when this one starts
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  # these fail fast on code errors
  sp4-pr:
    uses: ./.github/workflows/ScottPlot4-PR.yaml
    permissions:
      security-events: write
  sp5-pr:
    uses: ./.github/workflows/ScottPlot5-PR.yaml
    permissions:
      security-events: write

  # these take a long time to run and may commit back to main
  sp5-full:
    needs: [sp5-pr]
    uses: ./.github/workflows/ScottPlot5-Full.yaml
    permissions:
      security-events: write

  # the rest are misc tasks that may as well be run after merge to main
  security:
    name: Additional Security Scan
    needs: [sp4-pr, sp5-full]
    uses: ./.github/workflows/security.yaml
    permissions:
      security-events: write

  changelog:
    name: Analyze Code Metrics
    needs: [sp4-pr, sp5-full]
    uses: ./.github/workflows/tasks/publish-changelog.yaml
    permissions:
      security-events: write

  code-metrics:
    name: Analyze Code Metrics
    needs: [sp4-pr, sp5-full]
    uses: ./.github/workflows/tasks/code-metrics.yaml
    permissions:
      security-events: write
