# This workflow tests all code after any change to the main branch

name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**

# cancel running versions of this workflow when this one starts
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  # Run these jobs in parallel. Any one that errors will stop the rest.
  autoformat:
    name: "Task"
    uses: ./.github/workflows/task-autoformat-and-commit.yaml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  sp4-fast-build:
    name: "SP4"
    uses: ./.github/workflows/task-sp4-fast-build.yaml
    permissions:
      security-events: write
  sp4-full-build:
    name: "SP4"
    uses: ./.github/workflows/task-sp4-full-build.yaml
  sp5-pr:
    name: "SP5"
    uses: ./.github/workflows/ScottPlot5-PR.yaml
    permissions:
      security-events: write
  sp5-full:
    name: "SP5"
    uses: ./.github/workflows/ScottPlot5-Full.yaml

  # the rest of the jobs run only if the full build succeeds
  security:
    name: "Task"
    needs: [sp4-pr, sp5-full]
    uses: ./.github/workflows/task-security-scan.yaml
    permissions:
      security-events: write
  changelog:
    name: "Task"
    needs: [sp4-pr, sp5-full]
    uses: ./.github/workflows/task-publish-changelog.yaml
  code-metrics:
    name: "Task"
    needs: [sp4-pr, sp5-full]
    uses: ./.github/workflows/task-code-metrics.yaml
