# This workflow is for quick analysis of PRs.
# It finishes quickly and should gate merging of protected branches.

name: PR1

on:
  workflow_dispatch:
  pull_request:

jobs:
  sp4-check:
    uses: ./.github/workflows/task-sp4-check.yaml
    with:
      filters: |
        src:
          - 'src/ScottPlot4/**'
    permissions:
      security-events: write

  sp5-check:
    uses: ./.github/workflows/task-sp5-check.yaml
    with:
      filters: |
        src:
          - 'src/ScottPlot5/**'
    permissions:
      security-events: write
