# This workflow is for deep analysis of PRs.
# It takes a very long time to run so it should not block merging.

name: PR2

on:
  workflow_dispatch:
  pull_request:

jobs:
  sp4-full-build:
    uses: ./.github/workflows/task-sp4-full-build.yaml
    with:
      filters: |
        src:
          - 'src/ScottPlot4/**'
    permissions:
      security-events: write

  sp5-full-build:
    uses: ./.github/workflows/task-sp5-full-build.yaml
    with:
      filters: |
        src:
          - 'src/ScottPlot5/**'
    permissions:
      security-events: write

  autoformat-check:
    uses: ./.github/workflows/task-autoformat-check.yaml
    permissions:
      security-events: write
