# This is a quick action to verify PRs are in acceptable state.
# It does not build or test targets requiring exotic workloads.

name: PR

on:
  workflow_dispatch:
  pull_request:
    paths:
      - src/ScottPlot5/**

jobs:
  sp5-fast-build:
    name: "SP5"
    uses: ./.github/workflows/task-sp5-fast-build.yaml
  sp5-full-build:
    name: "SP5"
    uses: ./.github/workflows/task-sp5-full-build.yaml
