name: PR

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths:
      - src/ScottPlot4/**

concurrency:
  group: $SP4-{{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  SLN_SP4_TEST: "src/ScottPlot4/ScottPlot.Tests/ScottPlot.Tests.csproj"
  SLN_SP4_FULL: "src/ScottPlot4/ScottPlot4.sln"
  DOTNET_VERSION: "8.0.x"

jobs:
  test-linux:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3
      - name: ✨ Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: 🚚 Restore ScottPlot4
        run: dotnet restore "${{ env.SLN_SP4_TEST }}"
      - name: 🛠️ Build ScottPlot4
        run: dotnet build "${{ env.SLN_SP4_TEST }}" --configuration Release
      - name: 🧪 Test ScottPlot4
        run: dotnet test "${{ env.SLN_SP4_TEST }}" --configuration Release --verbosity minimal

  test-windows:
    needs: [test-linux]
    name: Full Build
    runs-on: windows-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3
      - name: 🐢 Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: ✨ Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: 🚚 Restore ScottPlot4
        run: dotnet restore ${{ env.SLN_SP4_TEST }}
      - name: 🛠️ Build ScottPlot4
        run: dotnet build ${{ env.SLN_SP4_TEST }} --configuration Release
      - name: 🧪 Test ScottPlot4
        run: dotnet test ${{ env.SLN_SP4_TEST }} --configuration Release --verbosity minimal
      - name: 🚚 Full Restore ScottPlot4
        run: dotnet restore ${{ env.SLN_SP4_FULL }}
      - name: 🛠️ Full Build ScottPlot4
        run: dotnet build ${{ env.SLN_SP4_FULL }} --configuration Release
      - name: ✒️ Check Code Formatting
        if: github.event_name == 'pull_request'
        run: |
          dotnet format --verify-no-changes ${{ env.SLN_SP4_FULL }}
          echo "::warning::Run 'dotnet format ScottPlot4.sln' to fix code format errors"
      - name: ✒️ Fix Code Formatting
        if: github.event_name != 'pull_request'
        run: |
          dotnet format ${{ env.SLN_SP4_FULL }}
          git config --global user.name 'Scott W Harden (via GitHub Actions)'
          git config --global user.email 'swharden@gmail.com'
          git pull
          git commit -am "CI: autoformat"
          git push