name: PR

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths:
      - src/ScottPlot5/**

concurrency:
  group: $SP5-{{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  SLN_SP5_TEST: "src/ScottPlot5/ScottPlot5 Tests/ScottPlot Tests.csproj"
  SLN_SP5_COOK: "src/ScottPlot5/ScottPlot5 Cookbook/ScottPlot Cookbook.csproj"
  SLN_SP5_DEMO: "src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/WinForms Demo.csproj"
  SLN_SP5_FULL: "src/ScottPlot5/ScottPlot5.sln"
  DOTNET_VERSION: "8.0.x"

jobs:
  test-linux:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3
      - name: ✨ Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: 🚚 Restore
        run: |
          dotnet restore "${{ env.SLN_SP5_TEST }}"
          dotnet restore "${{ env.SLN_SP5_COOK }}"
          dotnet restore "${{ env.SLN_SP5_DEMO }}"
      - name: 🛠️ Build
        run: |
          dotnet build "${{ env.SLN_SP5_TEST }}" --configuration Release
          dotnet build "${{ env.SLN_SP5_COOK }}" --configuration Release
          dotnet build "${{ env.SLN_SP5_DEMO }}" --configuration Release
      - name: 🧪 Run Tests
        run: |
          dotnet test "${{ env.SLN_SP5_TEST }}" --configuration Release --verbosity minimal
          dotnet test "${{ env.SLN_SP5_COOK }}" --configuration Release --verbosity minimal

  test-windows:
    needs: [test-linux]
    name: Full Build
    runs-on: windows-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3
      - name: 🐢 Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: ✨ Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: ✨ Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "microsoft"
          java-version: "17"
      - name: 🚚 Install Workloads
        run: dotnet workload install maui-android maui-ios maccatalyst wasm-tools
      - name: 🚚 Workload Restore
        run: dotnet workload restore "${{ env.SLN_SP5_FULL }}"
      - name: 🚚 Solution Restore
        run: dotnet restore "${{ env.SLN_SP5_FULL }}"
      - name: 🛠️ Full Build
        run: dotnet build "${{ env.SLN_SP5_FULL }}" --configuration Release
      - name: ✒️ Check Code Formatting
        if: github.event_name == 'pull_request'
        run: |
          dotnet format --verify-no-changes "${{ env.SLN_SP5_FULL }}"
          echo "::warning::Run 'dotnet format ScottPlot5.sln' to fix code format errors"
      - name: ✒️ Fix Code Formatting
        if: github.event_name != 'pull_request'
        run: |
          dotnet format ${{ env.SLN_SP5_FULL }}
          git config --global user.name 'Scott W Harden (via GitHub Actions)'
          git config --global user.email 'swharden@gmail.com'
          git pull
          git commit -am "CI: autoformat"
          git push