name: ScottPlot 5 Package

on:
  workflow_dispatch:

env:
  DOTNET_VERSION: "8.0.x"
  TEST_PROJECT_FOLDER: "src/ScottPlot5/ScottPlot5 Tests/"
  ARTIFACT_FOLDER: "artifacts"

jobs:
  deploy:
    name: 🚀 Publish ScottPlot5 Packages
    runs-on: windows-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4

      - name: ✨ Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 📦 Package ScottPlot
        env:
          PROJECT_FOLDER: "src/ScottPlot5/ScottPlot5"
        run: |
          dotnet restore "${{ env.PROJECT_FOLDER }}"
          dotnet build "${{ env.PROJECT_FOLDER }}" --configuration Release
          dotnet pack "${{ env.PROJECT_FOLDER }}" --configuration Release -o "${{ env.ARTIFACT_FOLDER }}"

      - name: 🚀 Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "ScottPlot"
          path: ${{ env.ARTIFACT_FOLDER }}
          if-no-files-found: error
          retention-days: 1
          overwrite: true
