name: PR

on:
  workflow_dispatch:
  pull_request:
    paths:
      - src/ScottPlot4/**

jobs:
  sp4-fast-build:
    name: "SP4"
    uses: ./.github/workflows/task-sp4-fast-build.yaml
    permissions:
      security-events: write

  sp4-full-build:
    name: "SP4"
    uses: ./.github/workflows/task-sp4-full-build.yaml
