name: "Security Analysis"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**

env:
  SLN_SP5_FULL: "src/ScottPlot5/ScottPlot5.sln"
  SLN_SP5_PROJ: "src/ScottPlot5/ScottPlot5/ScottPlot.csproj"
  SLN_SP5_TEST: "src/ScottPlot5/ScottPlot5 Tests/ScottPlot Tests.csproj"
  SLN_SP5_COOK: "src/ScottPlot5/ScottPlot5 Cookbook/ScottPlot Cookbook.csproj"
  SLN_SP5_DEMO: "src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/WinForms Demo.csproj"
  DOTNET_VERSION: "8.0.x"
  
jobs:
  analyze:
    name: Code Security Scan
    runs-on: ${{ (matrix.language == 'csharp' && 'windows-latest') || 'ubuntu-latest' }}
    permissions:
      security-events: write
      packages: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: csharp, python, javascript-typescript
        build-mode: manual
    - name: 🐢 Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: ✨ Setup .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: ✨ Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: "microsoft"
        java-version: "17"
    - name: 🚚 Install Workloads
      run: dotnet workload install maui-android maui-ios maccatalyst wasm-tools
    - name: 🚚 Workload Restore
      run: dotnet workload restore "${{ env.SLN_SP5_FULL }}"
    - name: 🚚 Solution Restore
      run: dotnet restore "${{ env.SLN_SP5_FULL }}"
    - name: 🛠️ Full Build
      run: dotnet build "${{ env.SLN_SP5_FULL }}" --configuration Release
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"
