# ScottPlot 4 fast build runs tests and performs security scan on linux

name: SP4 Fast Build

on:
  workflow_dispatch:
  workflow_call:

env:
  SLN_SP4_TEST: "src/ScottPlot4/ScottPlot.Tests/ScottPlot.Tests.csproj"
  SLN_SP4_FULL: "src/ScottPlot4/ScottPlot4.sln"
  DOTNET_VERSION: "8.0.x"

jobs:
  sp4-fast-build:
    name: Fast Build
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4
      - name: ⚙️ Setup CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp
          build-mode: manual
      - name: ✨ Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: 🚚 Restore
        run: dotnet restore "${{ env.SLN_SP4_TEST }}"
      - name: 🛠️ Build
        run: dotnet build "${{ env.SLN_SP4_TEST }}" --configuration Release
      - name: 🧪 Test
        run: dotnet test "${{ env.SLN_SP4_TEST }}" --configuration Release --verbosity minimal
      - uses: github/codeql-action/analyze@v3
