name: Full Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  full:
    name: Full Build
    runs-on: windows-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp
          build-mode: manual
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "17"
      - name: Install Workloads
        run: |
          dotnet workload install maui-android maui-ios maccatalyst wasm-tools
          dotnet workload restore "src\ScottPlot5\ScottPlot5.sln"
          dotnet workload restore "src\ScottPlot5\ScottPlot4.sln"
      - name: Build ScottPlot5
        run: |
          dotnet restore "src\ScottPlot4\ScottPlot5.sln"
          dotnet build "src\ScottPlot4\ScottPlot5.sln" --configuration Release
      - name: Build ScottPlot4
        run: |
          dotnet restore "src\ScottPlot4\ScottPlot4.sln"
          dotnet build "src\ScottPlot4\ScottPlot4.sln" --configuration Release
      - name: Run ScottPlot5 Unit Tests
        run: dotnet test "src\ScottPlot5\ScottPlot5 Tests\" --configuration Release --no-build --verbosity minimal
      - name: Run ScottPlot5 Cookbook Tests
        run: dotnet test "src\ScottPlot5\ScottPlot5 Cookbook\" --configuration Release --no-build --verbosity minimal
      - name: Run ScottPlot4 Tests
        run: dotnet test "src\ScottPlot4\ScottPlot.Tests\" --configuration Release --no-build --verbosity minimal
      - name: Security Scan
        uses: github/codeql-action/analyze@v3
