name: SP5 Full Build

on:
  workflow_dispatch:
  workflow_call:

env:
  SLN_SP5_FULL: "src/ScottPlot5/ScottPlot5.sln"
  DOTNET_VERSION: "8.0.x"

jobs:
  sp5-full:
    name: Full Build
    runs-on: windows-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4
      - name: ⚙️ Setup CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp
          build-mode: manual
      - name: 🐢 Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: ✨ Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: ✨ Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "17"
      - name: 🚚 Install Workloads
        run: dotnet workload install maui-android maui-ios maccatalyst wasm-tools
      - name: 🚚 Workload Restore
        run: dotnet workload restore "${{ env.SLN_SP5_FULL }}"
      - name: 🚚 Solution Restore
        run: dotnet restore "${{ env.SLN_SP5_FULL }}"
      - name: 🛠️ Full Build
        run: dotnet build "${{ env.SLN_SP5_FULL }}" --configuration Release
      - name: 🧪 Run Tests
        run: dotnet test "${{ env.SLN_SP5_FULL }}" --configuration Release
      - name: 🕵️ Security Scan
        uses: github/codeql-action/analyze@v3