# ScottPlot 4 full build builds the entire solution on windows

name: SP4 Full Build

on:
  workflow_dispatch:
  workflow_call:

env:
  SLN_SP4_TEST: "src/ScottPlot4/ScottPlot.Tests/ScottPlot.Tests.csproj"
  SLN_SP4_FULL: "src/ScottPlot4/ScottPlot4.sln"
  DOTNET_VERSION: "8.0.x"

jobs:
  sp4-full-build:
    name: Full Build
    runs-on: windows-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4
      - name: 🐢 Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: ✨ Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: 🚚 Restore
        run: dotnet restore ${{ env.SLN_SP4_TEST }}
      - name: 🛠️ Build
        run: dotnet build ${{ env.SLN_SP4_TEST }} --configuration Release
      - name: 🧪 Test
        run: dotnet test ${{ env.SLN_SP4_TEST }} --configuration Release --verbosity minimal
      - name: 🚚 Restore
        run: dotnet restore ${{ env.SLN_SP4_FULL }}
      - name: 🛠️ Build
        run: dotnet build ${{ env.SLN_SP4_FULL }} --configuration Release
